<a href="https://colab.research.google.com/github/Jaehyeonee/FSI-AIxData-Challenge-2024/blob/main/FIS_baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## To Do

- 컬럼 인코딩
  미해결 컬럼:

  (```Account_account_number, IP_Address, MAC_Address, Location, Distance, Time Difference```)



---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path = '/content/drive/MyDrive/Colab Notebooks/Daycon_Data/train.csv'

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv(file_path)
train.head(5)

,ID,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,TRAIN_000000,1980,male,이상호,BJWQxd-WBASPLJ,2003-01-06 18:38:01,B,0,1,0,...,2003-01-22 23:38:48,2003-01-22 23:38:48,1,1,1,0,0,0,m,2003-01-22 23:38:48
1,TRAIN_000001,1964,male,박상철,kurCwX-odPUXEt,2003-01-07 16:40:44,C,0,1,0,...,2003-01-21 21:29:08,2003-01-31 00:19:46,0,1,0,0,0,0,m,2003-01-19 21:29:08
2,TRAIN_000002,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,0,...,2003-01-31 07:13:28,2003-01-31 07:13:28,0,0,1,1,1,0,m,2003-01-31 07:13:28
3,TRAIN_000003,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,1,0,0,0,0,m,2003-01-31 07:13:28
4,TRAIN_000004,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,0,0,1,1,0,m,2003-01-31 07:13:28

In [ ]:
train.describe()

,Customer_Birthyear,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,Customer_flag_change_of_authentication_4,Customer_rooting_jailbreak_indicator,Customer_mobile_roaming_indicator,Customer_VPN_Indicator,Customer_flag_terminal_malicious_behavior_1,Customer_flag_terminal_malicious_behavior_2,...,Transaction_num_connection_failure,Another_Person_Account,Distance,Unused_terminal_status,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user
count,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,...,120000.000000,120000.0,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000
mean,1977.101658,0.761650,0.870608,0.760125,0.870200,0.073275,0.032892,0.072008,0.050567,0.096058,...,0.776125,1.0,161.156262,0.921050,0.424917,0.511658,0.492342,0.557517,1.053767,0.000258
std,15.773059,0.426076,0.335634,0.427009,0.336085,0.260588,0.178354,0.258503,0.219112,0.294672,...,1.112938,0.0,84.087296,0.269662,0.494332,0.499866,0.499943,0.909211,1.457519,0.016071
min,1950.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1964.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,95.530110,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1977.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.0,155.802819,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,1990.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,1.0,218.893869,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000
max,2004.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,1.0,612.485680,1.000000,1.000000,1.000000,1.000000,10.000000,17.000000,1.000000

In [ ]:
train.info() ## 결측값 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 64 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   ID                                             120000 non-null  object
 1   Customer_Birthyear                             120000 non-null  int64
 2   Customer_Gender                                120000 non-null  object
 3   Customer_personal_identifier                   120000 non-null  object
 4   Customer_identification_number                 120000 non-null  object
 5   Customer_registration_datetime                 120000 non-null  object
 6   Customer_credit_rating                         120000 non-null  object
 7   Customer_flag_change_of_authentication_1       120000 non-null  int64
 8   Customer_flag_change_of_authentication_2       120000 non-null  int64
 9   Customer_flag_change_of_authentication_3       120000 non-null  int64
 10  Customer_flag_change_of_authentication_4       120000 non-null  int64
 11  Customer_rooting_jailbreak_indicator           120000 non-null  int64
 12  Customer_mobile_roaming_indicator              120000 non-null  int64
 13  Customer_VPN_Indicator                         120000 non-null  int64
 14  Customer_loan_type                             120000 non-null  object
 15  Customer_flag_terminal_malicious_behavior_1    120000 non-null  int64
 16  Customer_flag_terminal_malicious_behavior_2    120000 non-null  int64
 17  Customer_flag_terminal_malicious_behavior_3    120000 non-null  int64
 18  Customer_flag_terminal_malicious_behavior_4    120000 non-null  int64
 19  Customer_flag_terminal_malicious_behavior_5    120000 non-null  int64
 20  Customer_flag_terminal_malicious_behavior_6    120000 non-null  int64
 21  Customer_inquery_atm_limit                     120000 non-null  int64
 22  Customer_increase_atm_limit                    120000 non-null  int64
 23  Account_account_number                         120000 non-null  object
 24  Account_account_type                           120000 non-null  object
 25  Account_creation_datetime                      120000 non-null  object
 26  Account_initial_balance                        120000 non-null  int64
 27  Account_balance                                120000 non-null  int64
 28  Account_indicator_release_limit_excess         120000 non-null  int64
 29  Account_amount_daily_limit                     120000 non-null  int64
 30  Account_indicator_Openbanking                  120000 non-null  int64
 31  Account_remaining_amount_daily_limit_exceeded  120000 non-null  int64
 32  Account_release_suspention                     120000 non-null  int64
 33  Account_one_month_max_amount                   120000 non-null  int64
 34  Account_one_month_std_dev                      120000 non-null  int64
 35  Account_dawn_one_month_max_amount              120000 non-null  int64
 36  Account_dawn_one_month_std_dev                 120000 non-null  int64
 37  Transaction_Datetime                           120000 non-null  object
 38  Transaction_Amount                             120000 non-null  int64
 39  Channel                                        120000 non-null  object
 40  Operating_System                               120000 non-null  object
 41  Error_Code                                     120000 non-null  object
 42  Transaction_Failure_Status                     120000 non-null  int64
 43  Type_General_Automatic                         120000 non-null  object
 44  IP_Address                                     120000 non-null  object
 45  MAC_Address                                    120000 non-null  object
 46  Access_Medium                                  120000 non-null  object
 47  Location                                       120000 non-null  object
 48  Recipient_Account_Number                       120000 non-null  object
 49  Transaction_num_connection_failure             120000 non-null  int64
 50  Another_Person_Account                         120000 non-null  int64
 51  Distance                                       120000 non-null  float64
 52  Time_difference                                120000 non-null  object
 53  Unused_terminal_status                         120000 non-null  int64
 54  Last_atm_transaction_datetime                  120000 non-null  object
 55  Last_bank_branch_transaction_datetime          120000 non-null  object
 56  Flag_deposit_more_than_tenMillion              120000 non-null  int64
 57  Unused_account_status                          120000 non-null  int64
 58  Recipient_account_suspend_status               120000 non-null  int64
 59  Number_of_transaction_with_the_account         120000 non-null  int64
 60  Transaction_history_with_the_account           120000 non-null  int64
 61  First_time_iOS_by_vulnerable_user              120000 non-null  int64
 62  Fraud_Type                                     120000 non-null  object
 63  Transaction_resumed_date                       120000 non-null  object
dtypes: float64(1), int64(38), object(25)
memory usage: 58.6+ MB

In [ ]:
train

,ID,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,TRAIN_000000,1980,male,이상호,BJWQxd-WBASPLJ,2003-01-06 18:38:01,B,0,1,0,...,2003-01-22 23:38:48,2003-01-22 23:38:48,1,1,1,0,0,0,m,2003-01-22 23:38:48
1,TRAIN_000001,1964,male,박상철,kurCwX-odPUXEt,2003-01-07 16:40:44,C,0,1,0,...,2003-01-21 21:29:08,2003-01-31 00:19:46,0,1,0,0,0,0,m,2003-01-19 21:29:08
2,TRAIN_000002,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,0,...,2003-01-31 07:13:28,2003-01-31 07:13:28,0,0,1,1,1,0,m,2003-01-31 07:13:28
3,TRAIN_000003,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,1,0,0,0,0,m,2003-01-31 07:13:28
4,TRAIN_000004,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,0,0,1,1,0,m,2003-01-31 07:13:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,TRAIN_119995,1991,female,유아름,MBpRXq-QfPDZwF,2010-08-23 09:16:18,C,0,1,0,...,2051-11-06 08:03:53,2051-09-12 07:41:31,0,1,1,0,0,0,m,2054-12-05 11:51:18
119996,TRAIN_119996,1991,female,장지은,PchfPH-CxuDqYG,2012-11-14 12:57:03,B,0,1,1,...,2053-12-28 18:59:17,2053-12-18 23:04:56,0,0,0,2,2,0,m,2055-12-31 07:07:51
119997,TRAIN_119997,2004,male,윤지훈,lEIytT-xVrZZIO,2024-07-15 06:28:05,B,1,1,0,...,2056-08-06 07:44:50,2056-07-31 16:38:49,0,1,0,0,0,0,m,2056-07-25 11:44:22
119998,TRAIN_119998,2004,female,김경희,JQKetZ-JOWiLRU,2024-05-12 00:31:19,A,1,1,1,...,2058-06-17 12:34:39,2058-06-06 09:25:05,0,1,0,0,0,0,m,2058-05-15 01:14:42
119999,TRAIN_119999,2004,female,김경희,JQKetZ-JOWiLRU,2024-05-12 00:31:19,A,1,1,1,...,2058-06-17 12:34:39,2058-06-24 12:21:34,0,1,1,0,0,0,m,2058-05-15 01:14:42

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Daycon_Data/train.csv')
test.head()

,ID,Customer_Birthyear,Customer_Gender,Customer_personal_identifier,Customer_identification_number,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,TRAIN_000000,1980,male,이상호,BJWQxd-WBASPLJ,2003-01-06 18:38:01,B,0,1,0,...,2003-01-22 23:38:48,2003-01-22 23:38:48,1,1,1,0,0,0,m,2003-01-22 23:38:48
1,TRAIN_000001,1964,male,박상철,kurCwX-odPUXEt,2003-01-07 16:40:44,C,0,1,0,...,2003-01-21 21:29:08,2003-01-31 00:19:46,0,1,0,0,0,0,m,2003-01-19 21:29:08
2,TRAIN_000002,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,0,...,2003-01-31 07:13:28,2003-01-31 07:13:28,0,0,1,1,1,0,m,2003-01-31 07:13:28
3,TRAIN_000003,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,1,0,0,0,0,m,2003-01-31 07:13:28
4,TRAIN_000004,1982,female,조옥자,OiERQa-CTXBoaX,2003-01-11 14:08:36,B,1,1,1,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,0,0,1,1,0,m,2003-01-31 07:13:28

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 64 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   ID                                             120000 non-null  object
 1   Customer_Birthyear                             120000 non-null  int64
 2   Customer_Gender                                120000 non-null  object
 3   Customer_personal_identifier                   120000 non-null  object
 4   Customer_identification_number                 120000 non-null  object
 5   Customer_registration_datetime                 120000 non-null  object
 6   Customer_credit_rating                         120000 non-null  object
 7   Customer_flag_change_of_authentication_1       120000 non-null  int64
 8   Customer_flag_change_of_authentication_2       120000 non-null  int64
 9   Customer_flag_change_of_authentication_3       120000 non-null  int64
 10  Customer_flag_change_of_authentication_4       120000 non-null  int64
 11  Customer_rooting_jailbreak_indicator           120000 non-null  int64
 12  Customer_mobile_roaming_indicator              120000 non-null  int64
 13  Customer_VPN_Indicator                         120000 non-null  int64
 14  Customer_loan_type                             120000 non-null  object
 15  Customer_flag_terminal_malicious_behavior_1    120000 non-null  int64
 16  Customer_flag_terminal_malicious_behavior_2    120000 non-null  int64
 17  Customer_flag_terminal_malicious_behavior_3    120000 non-null  int64
 18  Customer_flag_terminal_malicious_behavior_4    120000 non-null  int64
 19  Customer_flag_terminal_malicious_behavior_5    120000 non-null  int64
 20  Customer_flag_terminal_malicious_behavior_6    120000 non-null  int64
 21  Customer_inquery_atm_limit                     120000 non-null  int64
 22  Customer_increase_atm_limit                    120000 non-null  int64
 23  Account_account_number                         120000 non-null  object
 24  Account_account_type                           120000 non-null  object
 25  Account_creation_datetime                      120000 non-null  object
 26  Account_initial_balance                        120000 non-null  int64
 27  Account_balance                                120000 non-null  int64
 28  Account_indicator_release_limit_excess         120000 non-null  int64
 29  Account_amount_daily_limit                     120000 non-null  int64
 30  Account_indicator_Openbanking                  120000 non-null  int64
 31  Account_remaining_amount_daily_limit_exceeded  120000 non-null  int64
 32  Account_release_suspention                     120000 non-null  int64
 33  Account_one_month_max_amount                   120000 non-null  int64
 34  Account_one_month_std_dev                      120000 non-null  int64
 35  Account_dawn_one_month_max_amount              120000 non-null  int64
 36  Account_dawn_one_month_std_dev                 120000 non-null  int64
 37  Transaction_Datetime                           120000 non-null  object
 38  Transaction_Amount                             120000 non-null  int64
 39  Channel                                        120000 non-null  object
 40  Operating_System                               120000 non-null  object
 41  Error_Code                                     120000 non-null  object
 42  Transaction_Failure_Status                     120000 non-null  int64
 43  Type_General_Automatic                         120000 non-null  object
 44  IP_Address                                     120000 non-null  object
 45  MAC_Address                                    120000 non-null  object
 46  Access_Medium                                  120000 non-null  object
 47  Location                                       120000 non-null  object
 48  Recipient_Account_Number                       120000 non-null  object
 49  Transaction_num_connection_failure             120000 non-null  int64
 50  Another_Person_Account                         120000 non-null  int64
 51  Distance                                       120000 non-null  float64
 52  Time_difference                                120000 non-null  object
 53  Unused_terminal_status                         120000 non-null  int64
 54  Last_atm_transaction_datetime                  120000 non-null  object
 55  Last_bank_branch_transaction_datetime          120000 non-null  object
 56  Flag_deposit_more_than_tenMillion              120000 non-null  int64
 57  Unused_account_status                          120000 non-null  int64
 58  Recipient_account_suspend_status               120000 non-null  int64
 59  Number_of_transaction_with_the_account         120000 non-null  int64
 60  Transaction_history_with_the_account           120000 non-null  int64
 61  First_time_iOS_by_vulnerable_user              120000 non-null  int64
 62  Fraud_Type                                     120000 non-null  object
 63  Transaction_resumed_date                       120000 non-null  object
dtypes: float64(1), int64(38), object(25)
memory usage: 58.6+ MB

In [ ]:
test = test.drop(labels=['ID','Customer_personal_identifier','Customer_identification_number'],axis=1)
train = train.drop(labels=['ID','Customer_personal_identifier','Customer_identification_number'],axis=1)

In [ ]:
train_target = train['Fraud_Type'].value_counts()
print(train_target)

Fraud_Type
m    118800
a       100
j       100
h       100
k       100
c       100
g       100
i       100
b       100
f       100
d       100
e       100
l       100
Name: count, dtype: int64

m이 많이 존재함을 알 수 있음.

In [ ]:
# 범주형 데이터 원-핫 인코딩 수행
# 순서형 데이터 train['Customer_credit_rating'] 먼저 OrdinalEncoder 수행.
from sklearn.preprocessing import OrdinalEncoder

categories = [['S', 'A', 'B', 'C', 'D', 'E']]

# OrdinalEncoder 초기화 및 학습
encoder_train = OrdinalEncoder(categories=categories)
train['Customer_credit_rating'] = encoder_train.fit_transform(train[['Customer_credit_rating']])

# float형 변환 (선택사항)
train['Customer_credit_rating'] = train['Customer_credit_rating'].astype(float)



encoder_test= OrdinalEncoder(categories=categories)
test['Customer_credit_rating'] = encoder_test.fit_transform(test[['Customer_credit_rating']])

test['Customer_credit_rating'] = test['Customer_credit_rating'].astype(float)

In [ ]:
# 명목형 데이터 LabelEncoder 수행
from collections import defaultdict
from sklearn.preprocessing import LabelEncoder

class MultiColLabelEncoder:
    def __init__(self):
        self.encoder_dict = defaultdict(LabelEncoder)

    def fit_transform(self, X: pd.DataFrame, columns : list):
        if not isinstance(columns, list):
            columns = [columns]

        output = X.copy()
        output[columns] = X[columns].apply(lambda x:self.encoder_dict[x.name].fit_transform(x))

        return output

mcle = MultiColLabelEncoder()
columns = ['Customer_Gender',
           'Customer_loan_type',
           'Account_account_type',
           'Channel',
           'Operating_System',
           'Error_Code',
           'Type_General_Automatic',
           'Access_Medium']
transformed_data_train = mcle.fit_transform(train, columns = columns)
transformed_data_train.head()

transformed_data_test = mcle.fit_transform(test, columns = columns)
transformed_data_test.head()

,Customer_Birthyear,Customer_Gender,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,Customer_flag_change_of_authentication_4,Customer_rooting_jailbreak_indicator,Customer_mobile_roaming_indicator,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,1980,1,2003-01-06 18:38:01,2.0,0,1,0,1,0,0,...,2003-01-22 23:38:48,2003-01-22 23:38:48,1,1,1,0,0,0,m,2003-01-22 23:38:48
1,1964,1,2003-01-07 16:40:44,3.0,0,1,0,0,0,0,...,2003-01-21 21:29:08,2003-01-31 00:19:46,0,1,0,0,0,0,m,2003-01-19 21:29:08
2,1982,0,2003-01-11 14:08:36,2.0,1,1,0,0,0,0,...,2003-01-31 07:13:28,2003-01-31 07:13:28,0,0,1,1,1,0,m,2003-01-31 07:13:28
3,1982,0,2003-01-11 14:08:36,2.0,1,1,1,0,0,0,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,1,0,0,0,0,m,2003-01-31 07:13:28
4,1982,0,2003-01-11 14:08:36,2.0,1,1,1,0,0,0,...,2003-01-31 11:49:56,2003-01-31 07:13:28,1,0,0,1,1,0,m,2003-01-31 07:13:28

In [ ]:
from datetime import datetime

time_columns=['Customer_registration_datetime',
                      'Account_creation_datetime',
                      'Transaction_Datetime',
                      'Last_atm_transaction_datetime',
                      'Last_bank_branch_transaction_datetime',
                      'Transaction_resumed_date'
                      ]

for col in time_columns:
    # 문자열을 datetime으로 변환
    transformed_data_train[col] = pd.to_datetime(transformed_data_train[col])
    transformed_data_test[col] = pd.to_datetime(transformed_data_test[col])
    # datetime을 UNIX 타임스탬프(초)로 변환
    transformed_data_train[col] = transformed_data_train[col].astype(int) / 10 ** 9
    transformed_data_test[col] = transformed_data_test[col].astype(int) / 10 ** 9

transformed_data_train

,Customer_Birthyear,Customer_Gender,Customer_registration_datetime,Customer_credit_rating,Customer_flag_change_of_authentication_1,Customer_flag_change_of_authentication_2,Customer_flag_change_of_authentication_3,Customer_flag_change_of_authentication_4,Customer_rooting_jailbreak_indicator,Customer_mobile_roaming_indicator,...,Last_atm_transaction_datetime,Last_bank_branch_transaction_datetime,Flag_deposit_more_than_tenMillion,Unused_account_status,Recipient_account_suspend_status,Number_of_transaction_with_the_account,Transaction_history_with_the_account,First_time_iOS_by_vulnerable_user,Fraud_Type,Transaction_resumed_date
0,1980,1,1.000000e-09,2.0,0,1,0,1,0,0,...,1.043279,1.043279,1,1,1,0,0,0,m,1.043279
1,1964,1,1.000000e-09,3.0,0,1,0,0,0,0,...,1.043185,1.043972,0,1,0,0,0,0,m,1.043012
2,1982,0,1.000000e-09,2.0,1,1,0,0,0,0,...,1.043997,1.043997,0,0,1,1,1,0,m,1.043997
3,1982,0,1.000000e-09,2.0,1,1,1,0,0,0,...,1.044014,1.043997,1,1,0,0,0,0,m,1.043997
4,1982,0,1.000000e-09,2.0,1,1,1,0,0,0,...,1.044014,1.043997,1,0,0,1,1,0,m,1.043997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,1991,0,1.000000e-09,3.0,0,1,0,0,0,0,...,2.582871,2.578117,0,1,1,0,0,0,m,2.680084
119996,1991,0,1.000000e-09,2.0,0,1,1,0,0,0,...,2.650561,2.649712,0,0,0,2,2,0,m,2.713850
119997,2004,1,1.000000e-09,2.0,1,1,0,0,0,0,...,2.732773,2.732287,0,1,0,0,0,0,m,2.731751
119998,2004,0,1.000000e-09,1.0,1,1,1,1,0,0,...,2.791543,2.790581,0,1,0,0,0,0,m,2.788651
119999,2004,0,1.000000e-09,1.0,1,1,1,1,0,0,...,2.791543,2.792147,0,1,1,0,0,0,m,2.788651

In [ ]:
# transformed_train

In [ ]:
#데이터셋 분리
from sklearn.model_selection import train_test_split
X = transformed_data_train.drop(['Fraud_Type'],axis=1)
y= transformed_data_train['Fraud_Type']

x_train, x_val, y_train, y_val = train_test_split(X,y , test_size = 0.25,shuffle=True,random_state = 42)

In [ ]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (2.1.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.13.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (9.0.0)

## CatBoostClassifier 모델

In [ ]:
# CatBoostClassifier 모델 생성
from catboost import CatBoostClassifier
cbc = CatBoostClassifier(verbose = 200)
cbc.fit(x_train,y_train)
pred = cbc.predict(x_val)
print(accuracy_score(y_val,pred))

CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=20]="iJqABGzeJS": Cannot convert 'b'iJqABGzeJS'' to float

## RandomForest 모델

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# 랜덤 포레스트 모델 학습
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

# 모델 평가
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# 중요 피처 출력
importances = rf_model.feature_importances_
feature_importance = pd.Series(importances, index=X.columns).sort_values(ascending=False)
print("Feature Importances:\n", feature_importance)

- 특성 값의 스케일이 너무 다름 > 정규화 진행
- 랜포 모델로 꼽은 주요 피처를 기준으로 타 피처와의 상관관계를 분석하고 > 피처 집합으로 새 특성을 생성해서 cat boost모델 재학습